accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

app/urls.py
from django.urls import path
from . import views
from .views import post_result

app_name = 'app'

urlpatterns = [
            path('', views.index, name ='index'),
            path('viewer/', views.pdf_view, name ='pdf_view'),
            # path('result/', views.result, name = 'result'),
            path('request', views.post_result, name='post_result'),
            path('post_data', views.post_data, name ='post_data'),
]

ex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='app:index'), name='root'),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render,redirect
from django.views.generic import CreateView

# for signup 
signup = CreateView.as_view(
    form_class=UserCreationForm,
    template_name='form.html',
    success_url=settings.LOGIN_URL,
)

#for login
login = LoginView.as_view(
    template_name='form.html',
)

#for logout
logout = LogoutView.as_view(
    next_page='/app',
)

#access next to login
@login_required
def profile(request):
    return redirect('/app')

app/views.py
import json
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from . import search
from django.contrib.auth.decorators import login_required

# main window
def index(request):
    return render(request, 'app/index.html')

# nonmun page
@login_required #only to success login
def pdf_view(request):
    if request.method == 'GET':
        id ={'id':request.user}
        print(id['id'])
        return render(request, 'app/viewer.html',id)
        
    elif request.method == 'POST':
        text = {
                'title' : request.POST.get("search", None),
                'content' :request.POST.get("title", None) 
               }
        return render(request, 'app/viewer.html', text)

#searched data to HTML
@csrf_exempt
def post_result(request):
    # success  to POST data
    if request.method == 'POST':
        title = request.POST.get('search_title', None)
        content = request.POST.get('search_content', None)
        
        #keywords = search.searchDataContent(title,content)


        return JsonResponse(keywords)
    # Fail to POST data
    else:
        message = "임시 데이터. 적절하게 수정할 필요가 있다."
        context = {'secret_key': message }
        return JsonResponse(context)

#searching data from HTML
@csrf_exempt
def post_data(request):
    if request.method == 'POST':
        data = request.POST.get('title_data', None)
    return HttpResponse(data)

        

accounts/templates/profile.html
<h2>{{ user }}'s Profile</h2>

templates/app/index.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width">
		
        <title> 쿠딩 </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">  
    </head>
    <body>
        <style type = "text/css">
            .jumbotron {
                background-image: url('../../static/jumboBackground.jpg ');
                background-size: cover;
                text-shadow: black 0.2em 0.2em 0.2em;
                color: black;
            }
        </style>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
			
            <a class="navbar-brand" href= "{% url 'root' %}">
				<img src='{% static "kuding.jpg" %}'  class="img-rounded" width="100" height="100">Kuding</a>
            
          
            <div class="navbar navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto"></ul>
              <form class="form-inline my-2 my-lg-0">
				<div>
					{% if user.is_authenticated %}
						<a href="{% url 'logout' %}" class="btn btn-outline-success my-2 my-sm-0">로그아웃</a>
					{% else %}
						<a href="{% url 'login' %}" class="btn btn-outline-success my-2 my-sm-0">로그인</a>
						<a href="{% url 'signup' %}" class="btn btn-outline-success my-2 my-sm-0">회원가입</a>
					{% endif %}
				</div>
              </form>
            </div>
        </nav>
       
        <div class = "container">
            <div class = "jumbotron">
                <h1 class="text-center">쿠딩을 소개합니다</h1>
				<p class="text-center">건국대 학생들입니다</p>
				{% if user.is_authenticated %}
                <p class="text-center"><a class="btn btn-primary btn-lg" href="{% url 'app:pdf_view'%}" role = "button">논문 도움받으러 가기</a></p>
				{% else %}
				<p class="text-center"><a class="btn btn-primary btn-lg" href="{% url 'login' %}" role = "button">로그인을 해주세요</a></p>
				
				{% endif %}
				
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12 text-center">
                <h4>Kuding의 특징</h4>
                <p>논문을 보기쉽게 해줍니다</p>
            </div>
        </div>

        <footer style="background-color: #000000; color: #ffffff;">
            <div class = "container">
                <br>
                <div class = "row">
                    <div class = "col-sm-4" style="text-align: center;"><h5>Copyright &copy; 2020</h5><h5>Kuding</h5></div>
                    <div class = "col-sm-4"><h4>팀원 소개</h4><p>저희는 건국대학교 학생입니다</p></div>
                </div> 
            </div>
        </footer>
    </body>
</html>

templates/form.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
     <input type="submit" class="btn btn-danger" /> 
    </form>
{% endblock %}

templates/layout.html
{% load bootstrap4 %}
{% load static %}

<html>
<head>
    <link rel="icon"  href="{% static 'www/facvicon.ico' %}">
    <meta charset="utf-8" />
    <title>KUDING</title>
 
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    {% bootstrap_css %}
    {% bootstrap_jquery %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{% url 'root' %}" class="navbar-brand">
                    <img src='{% static "kuding.jpg" %}'   class="img-rounded" width="100" height="100">
                KUDING
            </a>

        

            <div>
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="btn btn-outline-info">로그아웃</a>
                {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-danger">로그인</a>
                    <a href="{% url 'signup' %}" class="btn btn-danger">회원가입</a>
                {% endif %}
            </div>
        </nav>

        <div class="card">
            <div class="card-body">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        &copy; 2020. kuding.
    </div>
</body>
</html>

templates/login/login.html
<div class = "raw">
    <div class = "col-12" >
      <div class = "col-12 text-center">
<h1>로그인</h1>
<br><br>

</div>
<form method = "POST">
  {% csrf_token %}
  
  <div class="form-group">
    <label for="username">사용자 이름</label>
    <input type="text" 
    class="form-control" 
    name = "username" 
    id="username" 
    placeholder="이름을 입력하세요">
  </div>

  <div class="form-group">
    <label for="password">비밀번호</label>
    <input type="password" 
    name = "password" 
    class="form-control" id="password" placeholder="비밀번호를 입력하세요">
  </div>


  <span style="color:red;"><strong>{{ error }}</strong> </span>
  <button type="submit" class="btn btn-primary">로그인</button>
</form>

templates/result/result.html
<!DOCTYPE html>
<html>
<head>
 <meta charset="UTF-8">
</head>
<body>
  <input type="button" id="hw" value="Hello world" />
    <script type="text/javascript">
        var hw = document.getElementById('hw');
        hw.addEventListener('click', function(){
            alert('Hello world');
        })
    </script>
<!--   
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    


  <a id="data_table">hihi{{search_key}}</a>
  <form id="form_search" method="POST">  {% csrf_token %}
    <fieldset id="search_fieldset">
      <input type="text" name="cd" id ="cd" value=""/>
      <input type="button" id="ch_button"  class = "btn btn-primary" value="검☆색"/>
    </fieldset> 
  </form>
  
  <script>
      alert(button);
    // $("#ch_button").click(function(){
    //   alert(button);
    //   var search_key = $("#cd").val();
    //   alert(search_key);
    //   $.ajax({ 
    //     type: "POST",
    //     url: '/app/request', 
    //     data : JSON.stringify({ 
    //         'search_key':search_key}
    //     ), 
    //     contentType: "application/json",
    //     success:function(data){ 
    //       $("#data_table").html(data[search_key]); 
    //     }, 
    //     error: function(request, status, error) {
    //         alert(error);
    //     }
    //   });
    // });
</script> -->

</body>
</html>